# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Category.create!(:name => "食費")
Category.create!(:name => "日用品")
Category.create!(:name => "交通費")
Category.create!(:name => "趣味・娯楽")
Category.create!(:name => "衣服・美容")
Category.create!(:name => "交際費")
Category.create!(:name => "健康・医療")
Category.create!(:name => "教育・教養")
Category.create!(:name => "水道・光熱費")
Category.create!(:name => "通信費")
Category.create!(:name => "住宅")
Category.create!(:name => "車・バイク")
Category.create!(:name => "税金")
Category.create!(:name => "保険")
Category.create!(:name => "特別な支出")
Category.create!(:name => "その他")
Category.create!(:name => "未分類")

MiniCategory.create!(:category_id =>"1", :name => "食費")
MiniCategory.create!(:category_id =>"1", :name => "食料品")
MiniCategory.create!(:category_id =>"1", :name => "外食")
MiniCategory.create!(:category_id =>"1", :name => "朝ごはん")
MiniCategory.create!(:category_id =>"1", :name => "昼ごはん")
MiniCategory.create!(:category_id =>"1", :name => "夜ごはん")
MiniCategory.create!(:category_id =>"1", :name => "カフェ")
MiniCategory.create!(:category_id =>"1", :name => "その他食費")

MiniCategory.create!(:category_id =>"2", :name => "日用品")
MiniCategory.create!(:category_id =>"2", :name => "ドラッグストア")
MiniCategory.create!(:category_id =>"2", :name => "子育て用品")
MiniCategory.create!(:category_id =>"2", :name => "ペット用品")
MiniCategory.create!(:category_id =>"2", :name => "タバコ")
MiniCategory.create!(:category_id =>"2", :name => "その他日用品")

MiniCategory.create!(:category_id =>"3", :name => "交通費")
MiniCategory.create!(:category_id =>"3", :name => "電車")
MiniCategory.create!(:category_id =>"3", :name => "バス")
MiniCategory.create!(:category_id =>"3", :name => "タクシー")
MiniCategory.create!(:category_id =>"3", :name => "飛行機")
MiniCategory.create!(:category_id =>"3", :name => "その他交通費")

MiniCategory.create!(:category_id =>"4", :name => "レジャー・スポーツ")
MiniCategory.create!(:category_id =>"4", :name => "イベント")
MiniCategory.create!(:category_id =>"4", :name => "映画・動画")
MiniCategory.create!(:category_id =>"4", :name => "音楽・ゲーム・漫画")
MiniCategory.create!(:category_id =>"4", :name => "本")
MiniCategory.create!(:category_id =>"4", :name => "旅行")
MiniCategory.create!(:category_id =>"4", :name => "その他趣味・娯楽")

MiniCategory.create!(:category_id =>"5", :name => "衣服")
MiniCategory.create!(:category_id =>"5", :name => "アクセサリー・小物")
MiniCategory.create!(:category_id =>"5", :name => "下着")
MiniCategory.create!(:category_id =>"5", :name => "美容院・理髪")
MiniCategory.create!(:category_id =>"5", :name => "化粧品")
MiniCategory.create!(:category_id =>"5", :name => "エステ・ネイル")
MiniCategory.create!(:category_id =>"5", :name => "クリーニング")
MiniCategory.create!(:category_id =>"5", :name => "その他衣服・美容")

MiniCategory.create!(:category_id =>"6", :name => "交際費")
MiniCategory.create!(:category_id =>"6", :name => "飲み会")
MiniCategory.create!(:category_id =>"6", :name => "プレゼント")
MiniCategory.create!(:category_id =>"6", :name => "冠婚葬祭")
MiniCategory.create!(:category_id =>"6", :name => "その他交際費")

MiniCategory.create!(:category_id =>"7", :name => "フィットネス")
MiniCategory.create!(:category_id =>"7", :name => "マッサージ・整体")
MiniCategory.create!(:category_id =>"7", :name => "病院")
MiniCategory.create!(:category_id =>"7", :name => "薬代")
MiniCategory.create!(:category_id =>"7", :name => "その他健康・医療")

MiniCategory.create!(:category_id =>"8", :name => "書籍")
MiniCategory.create!(:category_id =>"8", :name => "新聞・雑誌")
MiniCategory.create!(:category_id =>"8", :name => "習い事")
MiniCategory.create!(:category_id =>"8", :name => "教科書・参考書")
MiniCategory.create!(:category_id =>"8", :name => "学費")
MiniCategory.create!(:category_id =>"8", :name => "塾")
MiniCategory.create!(:category_id =>"8", :name => "その他教育・教養")

MiniCategory.create!(:category_id =>"9", :name => "光熱費")
MiniCategory.create!(:category_id =>"9", :name => "電気代")
MiniCategory.create!(:category_id =>"9", :name => "水道代")
MiniCategory.create!(:category_id =>"9", :name => "ガス・灯油代")
MiniCategory.create!(:category_id =>"9", :name => "その他水道・光熱費")

MiniCategory.create!(:category_id =>"10", :name => "携帯電話")
MiniCategory.create!(:category_id =>"10", :name => "固定電話")
MiniCategory.create!(:category_id =>"10", :name => "インターネット")
MiniCategory.create!(:category_id =>"10", :name => "放送視聴料")
MiniCategory.create!(:category_id =>"10", :name => "情報サービス")
MiniCategory.create!(:category_id =>"10", :name => "宅配便・運送")
MiniCategory.create!(:category_id =>"10", :name => "その他通信費")

MiniCategory.create!(:category_id =>"11", :name => "家賃")
MiniCategory.create!(:category_id =>"11", :name => "住宅ローン")
MiniCategory.create!(:category_id =>"11", :name => "管理費・積立金")
MiniCategory.create!(:category_id =>"11", :name => "家具")
MiniCategory.create!(:category_id =>"11", :name => "家電")
MiniCategory.create!(:category_id =>"11", :name => "リフォーム")
MiniCategory.create!(:category_id =>"11", :name => "地震・火災保険")
MiniCategory.create!(:category_id =>"11", :name => "その他住宅")

MiniCategory.create!(:category_id =>"12", :name => "ガソリン")
MiniCategory.create!(:category_id =>"12", :name => "駐車場")
MiniCategory.create!(:category_id =>"12", :name => "道路料金")
MiniCategory.create!(:category_id =>"12", :name => "自動車ローン")
MiniCategory.create!(:category_id =>"12", :name => "自動車保険")
MiniCategory.create!(:category_id =>"12", :name => "自動車税")
MiniCategory.create!(:category_id =>"12", :name => "車検・整備")
MiniCategory.create!(:category_id =>"12", :name => "その他車・バイク")

MiniCategory.create!(:category_id =>"13", :name => "所得税・住民税")
MiniCategory.create!(:category_id =>"13", :name => "年金")
MiniCategory.create!(:category_id =>"13", :name => "健康保険")
MiniCategory.create!(:category_id =>"13", :name => "その他税")

MiniCategory.create!(:category_id =>"14", :name => "保険")
MiniCategory.create!(:category_id =>"14", :name => "生命保険")
MiniCategory.create!(:category_id =>"14", :name => "医療保険")
MiniCategory.create!(:category_id =>"14", :name => "その他保険")

MiniCategory.create!(:category_id =>"15", :name => "特別な支出")
MiniCategory.create!(:category_id =>"15", :name => "結婚")
MiniCategory.create!(:category_id =>"15", :name => "妊活・出産")
MiniCategory.create!(:category_id =>"15", :name => "介護")
MiniCategory.create!(:category_id =>"15", :name => "その他特別な出費")

MiniCategory.create!(:category_id =>"16", :name => "その他")

MiniCategory.create!(:category_id =>"17", :name => "未分類")
